#!/usr/bin/env python3

import os
import time

base = '/Users'
for sub in os.listdir(base):
    path = os.path.join(base,sub)
    if os.path.isdir(path):
        lmod = os.path.getmtime(path)
        days_old = int((time.time() - lmod) / 86400)
        # print(path + ": " + str(days_old))
        if days_old < 1:



